### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by milovanderlinden** [simplerisk/code#18]
I would like to be able to use simplerisk as docker container(s).

**Comment by jsokol** [comment]
I've actually been playing around with a Dockerfile to do this.  I believe I finally got it working a couple of weeks ago.  If you'd like, send an email to support AT simplerisk.com and I'll hook you up with it with the caveat that it's purely experimental at this point.

**Comment by milovanderlinden** [comment]
I have a working docker setup using docker-compose in my fork at https://github.com/vulnis/code it uses a _sidekick_ installer to initialize the database. I opened this issue to facilitate a pull request later on.

**Comment by milovanderlinden** [comment]
I am actually using docker for development. 

The trick is to add a volume pointing to the `./simplerisk` directory:
```
volumes:
    - ./simplerisk:/var/www/html
```
I go into the `code` directory, run `docker-compose up` once per development session and that enables me to do live changes to the php files. This is the only way for me to have a working php5 environment as my Archlinux desktop has php7. It also eliminates the need for me to install mysql/mariadb and apache.

My full docker-compose file:
```
version: '3'

services:
  installer:
    build:
      context: ./installer
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=simplerisk
      - MYSQL_USER=simplerisk
      - MYSQL_PASSWORD=simplerisk
      - MYSQL_ROOT_PASSWORD=simplerisk
    links:
      - db
  simplerisk:
    build:
      context: ./
    depends_on:
      - db
      - installer
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=simplerisk
      - MYSQL_USER=simplerisk
      - MYSQL_PASSWORD=simplerisk
    links:
      - db
    volumes:
    - ./simplerisk:/var/www/html
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=simplerisk
```
